### PR TITLE
some little change

### PR DESCRIPTION
**Pull request by xiaopangju**
I don’t know if these changes meet your requirements, so I only copied the source code for a few pages. If I have done something wrong, please correct me.

### CODE REVIEW

**Comment by ShizuhaAki** [comment]
The evangelion one is a pseudonamespace, it is simply named that way. Another impact should be renamed with the evangelion prefix and moved to the main folder.

**Comment by ShizuhaAki** [comment]
Everything else is done correctly, thank you!

**Comment by xiaopangju** [comment]
> The evangelion one is a pseudonamespace, it is simply named that way. Another impact should be renamed with the evangelion prefix and moved to the main folder.

Thank you for your advice, so can you tell me how can I tell which namespaces the page belongs to?

**Comment by ShizuhaAki** [comment]
Usually work names are NOT a namespace.

**Comment by ShizuhaAki** [comment]
Namespaces we concern are (usually) only main,template, help, and project.

**Pull request merged**
